#!/bin/sh

echo "Checking code formatting"

cd ./ktlint-spring; ./gradlew ktlintCheck --daemon; cd ../;

status=$?

if [ "$status" == 0 ] ; then
	echo "No formatting issues were found"
	exit 0
else
	echo>&2 "* There are code formatting issues that must be addressed"
	exit 1
fi